name: namma_wallet
description: "Namma Wallet is an open-source project developed by the community
  members of Namma Flutter"
publish_to: "none"
version: 0.0.3+9

environment:
  sdk: "3.10.7"
  flutter: "3.38.6"

dependencies:
  ai_barcode_scanner: ^7.1.0
  archive: ^4.0.7
  card_stack_widget: ^0.1.6
  cross_file: ^0.3.5+1
  cupertino_icons: ^1.0.8
  dart_mappable: ^4.6.1
  dotted_border: ^3.1.0
  file_picker: ^10.3.8
  flutter:
    sdk: flutter
  flutter_gemma: ^0.12.0
  flutter_native_splash: ^2.4.7
  flutter_svg: ^2.2.3
  gaimon: ^1.4.2
  get_it: ^9.2.0
  go_router: ^17.0.1
  google_fonts: ^7.0.0
  google_mlkit_text_recognition: ^0.15.0
  home_widget: ^0.9.0
  http: ^1.6.0
  image: ^4.7.2
  intl: ^0.20.2
  listen_sharing_intent:
    git:
      url: https://github.com/Zverik/receive_sharing_intent
      ref: v1.9.2
  meta: ^1.17.0
  package_info_plus: ^9.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  path_provider_platform_interface: ^2.1.2
  pdfrx: ^2.2.24
  pkpass: ^2.2.0
  plugin_platform_interface: ^2.1.8
  provider: ^6.1.5+1
  qr_flutter: ^4.1.0
  share_handler: ^0.0.25
  shared_preferences: ^2.5.4
  sqflite: ^2.4.2
  sqflite_common_ffi_web: ^1.1.1
  syncfusion_flutter_pdf: ^32.1.22
  table_calendar: ^3.2.0
  talker_flutter: ^5.1.9
  url_launcher: ^6.3.2
  uuid: ^4.5.2
  workmanager: ^0.9.0+3

dev_dependencies:
  build_runner: ^2.10.4
  change_app_package_name: ^1.5.0
  dart_mappable_builder: ^4.6.3
  flutter_gen_runner: ^5.12.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  mockito: ^5.6.1
  sqflite_common_ffi: ^2.4.0+2
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true

flutter_gen:
  output: lib/src/features/common/generated/
  line_length: 80

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app-icon-android-foreground.png"
  image_path_ios: "assets/icon/app-icon-iOS-Default.png"

flutter_native_splash:
  # Light theme configuration
  color: "#FFFFFF"
  image: assets/icon/splash_icon.png

  # Dark theme configuration
  color_dark: "#000000"
  image_dark: assets/icon/splash_icon.png

  android_12:
    image: assets/icon/splash_icon.png
    color: "#FFFFFF"
    image_dark: assets/icon/splash_icon.png
    color_dark: "#000000"

  fullscreen: true
